### ISSUE TITLE
Response of write and delete endpoint

### ISSUE THREAD

**Issue by steffansluis** [cayleygraph/cayley#627] opened 2017-08-22 13:42 UTC
I've been working on writing some integration tests using CircleCI 2.0 and the `quay.io/cayleygraph/cayley` image. I ran into some strange behavior while looking at the responses of the `/api/v1/write` and `/api/v1/delete` endpoint.

- When deleting one non-existing quad, the delete endpoint always returns `Successfully deleted 1 quads.`. It also does not delete the quad.
- When writing the same quad multiple times with the bare `quay.io/cayleygraph/cayley`, the write endpoint always returns `Successfully wrote 1 quads.` It does seems to write the quad, as returning the first 100 quads via the GraphQL API contains the written quad.

I'm guessing this strange behavior has something to do with the fact that I haven't passed a data volume (seeing as this is running in CircleCI 2.0), however it seems to me that either it should break more explicitly or it should work the way it's saying it does based on the responses I'm getting. Also, the delete endpoint seems to behave this way in normal circumstances as well, as I tested it on one of my production servers.

Reproducing the error:
- `docker run -d quay.io/cayleygraph/cayley`
- `docker exec -i -t ${contained_id} /bin/bash`
- Write quad: `curl 'http://localhost:64210/api/v1/write' --data '[{"subject":"<subject>","predicate":"<predicate>","object":"object","label":""}]' --compressed`
- Delete quad: `curl 'http://localhost:64210/api/v1/delete' --data '[{"subject":"<subject>","predicate":"<predicate>","object":"object","label":""}]' --compressed`
- List quads: `curl 'http://localhost:64210/api/v1/query/graphql' --data $'{\n  nodes(first: 100){\n    id\n  }\n}' --compressed`

**Comment by steffansluis** [comment] 2017-08-22 14:06
Update: Passing a data volume doesn't seem to fix the strange write behavior. The production server I tested on used a Postgres backend, so it might just be BoltDB that is behaving strangely with respect to writes. The strange delete behavior also occurs on the Postgres-backed Cayley instance.

**Comment by dennwc** [comment] 2017-08-22 14:55
There are multiple issues here:

1) Quad delete API does not return any indication of quad being actually removed (https://github.com/cayleygraph/cayley/issues/608)
2) Quad write has no indication of how many unique quads were written
3) Some backends will not garbage-collect nodes (https://github.com/cayleygraph/cayley/issues/617). Your last query shows nodes, not quads. Try `curl http://localhost:64210/api/v2/read` instead.

Issues 1 and 3 are tracked separately. And do you have a use case where issue 2 matters? Is it related to transactions?

Also I would suggest to switch to v2 api, if possible.

**Comment by steffansluis** [comment] 2017-08-22 15:22
My usecase for issue 2 is that I'm trying to deduplicate a stream of quads by writing them and filtering the result stream based on the response from Cayley. As for the `v2` api, it seems to suffer from issue 2 as well, but it fixes issue 1:
- `curl 'http://localhost:64210/api/v2/write' --data '<subject> <predicate> "object" .' --compressed` results in `{"result": "Successfully wrote 1 quads.", "count": 1}`, even after already writing the quad.
- `curl 'http://localhost:64210/api/v2/delete' --data '<subject> <predicate> "object" .' --compressed` deletes the quad correctly! Resulting in `{"result": "Successfully deleted 1 quads.", "count": 1}` and `{"error": "delete \u003csubject\u003e -- \u003cpredicate\u003e -\u003e \"object\": quad does not exist"}` consequently, which is what I would expect.

**Comment by dennwc** [comment] 2017-08-22 15:32
OK, I see the cause of the problem now. In v0.6 the default behavior was to report if duplicated quad was inserted. But it was a non-intuitive, since most large datasets contains duplicates. So we switched behavior, and now Cayley server ignores duplicates by default.

The fix would be to set ignore_duplicates to false in config:
```yaml
load:
  ignore_duplicates: false
```

**Comment by steffansluis** [comment] 2017-08-22 15:36
Aah, I see! I have to say, I didn't know this was a config option or that there was a `v2` API. Neither seem to be documented in the docs folder. However, I think this will solve my issues!

**Comment by dennwc** [comment] 2017-08-22 15:39
Yeah, our docs is a bit outdated. We will address it at least partially for 0.7 release.

I'm closing this, but feel free to reopen.

**Closed by dennwc** 2017-08-22 15:39 UTC
