### ISSUE TITLE
Gizmo + Bolt: crashes on counting all quads

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#874] opened 2019-10-15 13:25 UTC
**Description**
When executing:
```javascript
g.V()
.out()
.count()
```
Cayley crashes :(

**Comment by dennwc** [comment] 2020-01-11 16:23
Cannot reproduce nor on Bolt nor on memstore (latest `master`). Need a reproducer. Closing for now, but feel free to reopen.

**Closed by dennwc** 2020-01-11 16:23 UTC
Labels: backends, bug
