### ISSUE TITLE
ToArray not serializing to JSON as an array.

### ISSUE THREAD

**Issue by neonstalwart** [cayleygraph/cayley#171] opened 2014-10-09 21:10 UTC
using the testdata.nq database served via http, the following query

``` js
g.V('dani').Save('is').ForEach(function (item) { 
  item.follows = g.V(item.id).Out('follows').ToArray();
  g.Emit(item);
})
```

produces the incorrect response

``` json
{
 "result": [
  {
   "follows": "charlie,alice",
   "id": "dani",
   "is": "not cool"
  }
 ]
}
```

the `"follows"` property should be an array:

```
"follows": [ "charlie", "alice" ]
```

**Comment by robertmeta** [comment] 2016-07-10 02:20
This just returns null for me at this point.  Maybe too stale?  Going to close and if someone wants me to double check it I will.

**Comment by dennwc** [comment] 2016-07-10 02:40
I will double-check this later. May still be there.

**Comment by lnshi** [comment] 2017-01-11 08:44
@robertmeta For me also, just return null, no idea why, if change to `All()` then I am able to get back the actual values, it seems `ToValue()` also returns null
@dennwc

**Comment by dennwc** [comment] 2017-01-11 10:43
@lnshi Can you share an example query for me? I'm suspecting you are not calling `Emit` for these functions. `All` calls `Emit` automatically, while other functions you mentioned return an JS value, that can be later used to `Emit` results.

**Comment by lnshi** [comment] 2017-01-12 12:38
@dennwc  For `ToArray()`, `ToValue()`, `TagArray()`, `TagValue()` where should I call `Emit`?

My environment is Node.js, I don't have clear idea about should I or should not I implement the `Emit` function in the Node.js client, if yes, how should I implement the `Emit` function?

BTW, I want to apply cayley into one of my Node.js project, but those Node.js clients for cayley on github currently is far from can be called a proper lib, let alone using it in production, include the one put in cayley's README, it is kind of messy and hard to maintain and contribute to.

So I spent last two weeks built a new one, and already published to NPM and Github, it is here: [**Node.js Cayley Client**](https://github.com/lnshi/node-cayley), it is a lot better, I wrote all the mocha+chai test cases for All APIs.

For this issue the query example / test cases you can find in the test folder here: [Test cases: line 176](https://github.com/lnshi/node-cayley/blob/master/test/apis/callback.js)

Any more information I can provide?

Or any suggestions/correction to the [**New Node.js Cayley Client**](https://github.com/lnshi/node-cayley)

**Comment by dennwc** [comment] 2017-01-12 20:57
@lnshi `ToArray` may be used this way:

```javascript
// arr stores query results in form of JS array
var arr = g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").ToArray()

// emit arrays as a single result item in Cayley response
g.Emit(arr)

// emit each item as a separate result in Cayley response (same as All)
for (i in arr) {
  g.Emit(arr[i])
}
```
Other functions are similar, but returns different result types.

Library looks really good! Well done :) We should probably add it to our readme/docs, so more people can find it.

As a note, https://github.com/cayleygraph/cayley/pull/513 was merged recently, and we will deprecate "gremlin" query language name in 0.7 release. New name will be "gizmo", to avoid further confusion with original Gremlin. Queries will stay the same, and should work as usual. Also, "gremlin" name will still work in upcoming 0.6.1 release in case of regressions or bugs in new JS VM we use.

**Comment by lnshi** [comment] 2017-01-13 05:23
@dennwc  Thank you very much, lets add [the lib](https://github.com/lnshi/node-cayley) to Cayley's README/docs, so more people can find it easily and report the potential issues, later I will also add the guide for how to set Cayley up in localhost with Docker and MongoDB for running all the `mocha_chai` test cases.

And also I will follow the Cayley's release notes tightly to make the necessary changes.

To this issue, I am still a bit confused:

1. According to the doc the `ToArray()` will do the real query to Cayley server just like `All()`, and the client supposed to get something back from Cayley server, but now the response body from Cayley server is `null`, that is above your `var arr = g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").ToArray()`   `arr` will be `null`, so the client get nowhere and no chance to call the `Emit`.

2. How should the client lib implement the `Emit` function? As my understanding:

    - `Emit` function should be totally hided in any client lib.
    - Only keep in mind that when in some APIs you get the chance to pass some function to the Cayley server side, then you can use `g.Emit(data)`, like what I did in the test case for `query.ForEach(callback), query.ForEach(limit, callback)`, [test case for `ForEach`, line:247](https://github.com/lnshi/node-cayley/blob/master/test/apis/callback.js) , and it worked as I expected:

        ```
        it('query.ForEach(limit, gremlinCallback, callback)', function(done) {
          pickRandomly(pickRandomly(cayleyInstancePools)).g.type('query')
            .V("</user/shortid/23TplPdS>").In().ForEach(1, function(data) {
              g.Emit(data);
            }, function(err, resBody) {
              if (err) {
                done(err);
              } else {
                try {
                  assert.isArray(resBody.result);
                  expect(resBody.result).to.have.length.most(1, 'https://github.com/cayleygraph/cayley/issues/518');
                  done();
                } catch (e) {
                  done(e);
                }
              }
            });
        });
        ```

**Comment by dennwc** [comment] 2017-01-13 10:44
@lnshi If `g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").All()` works for you, then `var arr = g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").ToArray()` should properly set `arr` _server-side_ and send back _null_ result. For client to receive results from `arr`, `Emit` call should be included into query sent to the server, as shown in example I sent previously. Client should not implement Emit.

**Comment by lnshi** [comment] 2017-01-13 11:18
You mean send all of this as string in one HTTP call? Or else multiple http calls i don't  think serve has any way to maintain the context.

```
// arr stores query results in form of JS array
var arr = g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").ToArray()

// emit arrays as a single result item in Cayley response
g.Emit(arr)

// emit each item as a separate result in Cayley response (same as All)
for (i in arr) {
  g.Emit(arr[i])
}
```

That is my point, like this may will work, but i don't think it's the best way, why not we design it to make the client just like calling the local function chain , totally don't need to aware he is constructing  a piece of JavaScript code string, just like the `ForEach(callback)`

**Comment by dennwc** [comment] 2017-01-13 11:23
I mean that this is one query that should be sent to Cayley server:
```
var arr = g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").ToArray(); g.Emit(arr)
```
The whole point of `ToArray` is to allow users to retrieve array and do some operation on it server-side and then send some custom result using `Emit`.

If the library you are building will only use `ForEach`, it's totally fine to not proxy `ToArray`, since it will do effectively the same.

**Comment by lnshi** [comment] 2017-01-13 12:35
@dennwc  Thank you very much.

Yes, I got you, and also got the whole point of `ToArray()`, I am just trying to find out a way to 100% seamlessly proxy all the APIs provided by the server side and also keep 100% consistent with the Cayley's doc(in case confusing the user somehow ), and also make the lib user totally don't aware he is constructing any JavaScript code string which will be sent to server side.

Like `ToArray()`, I can hide the implementation details in the lib, then provide the API like this: `ToArray(gizmoCallback, callback)`, then the lib user can use it just like a local function call chain:
```
g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").ToArray(function(data) {
  g.Emit(data);
  for (let item in data) {
    let wantedData = (Apply the server side logic you want here....);
    g.Emit(wantedData);
  }
}, function(err, resBody) {// Server response});
```

Then the lib will transparently convert the above code to:
```
var data = g.V("</user/shortid/23TplPdS>").Tag("userId").In("<follows>").ToArray(); g.Emit(data); for (let item in data) {let wantedData = (Apply the server side logic you want here....);g.Emit(wantedData);}
```

The problem here is you see:

in Cayley's doc the `ToArray()` has no arguments, but in the client lib it get one `function`, so the signature is different, will confuse the user a bit.

So if the `ToArray()`'s signature can be just like `query.ForEach(callback)`, then it is perfect.

But I guess this is just a small issue,  if no other better way I will implement it like the way I explained above.

**Comment by dennwc** [comment] 2017-01-13 13:02
@lnshi Interesting approach. I like the way `ToArray` callback is seamlessly translated to Gizmo query. But I think we can't make ToArray to have a callback (or only a callback), since it will affect performance. Maybe it's better to document the difference?

**Comment by lnshi** [comment] 2017-01-13 13:17
@dennwc Ok, then I will do in above way, and then document the difference, and also leave the reference to this topic in the lib doc.

After done and passed the test I will come back to close this issue.

**Comment by lnshi** [comment] 2017-01-15 12:57
@dennwc 

Has done the above way implementation for `ToArray()`.

With commit [https://github.com/lnshi/node-cayley/commit/2ea9a4689f15827da6655e8ec2d86dc2def8437e](https://github.com/lnshi/node-cayley/commit/2ea9a4689f15827da6655e8ec2d86dc2def8437e), `ToArray()` works as expected, and passed the test case [query.ToArray() line:144](https://github.com/lnshi/node-cayley/blob/master/test/apis/callback.js), so I think this issue can be closed.

**Closed** 2017-01-15 14:22 UTC
Labels: state: try reproduce
