### ISSUE TITLE
Gizmo Bytecode

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#824] opened 2019-09-17 22:34 UTC
**Description**
Gizmo is pretty slow compared to other querying languages as it requires booting a full blown JavaScript interpreter. To solve it we can make Gizmo to work on a bytecode created by client libraries similarly to [Gremlin](http://tinkerpop.apache.org/docs/current/tutorials/gremlin-language-variants/). The bytecode will also reduce the complexity of maintaining clients in different languages as it will only require to build a simple data-structure instead of JavaScript valid string.
This should somewhat solve #556

**Comment by dennwc** [comment] 2019-09-18 13:37
If we decide to go down to the bytecode road (which I also consider, especially for custom graph algorithms), I propose to use [WebAssembly](https://webassembly.org/) instead.

There are already a few projects that implement WASM runtimes for Go and/or CGo, and the compiler compatibility story will be a lot better.

For that to happen, we need to wait until [WASI](https://wasi.dev/) specification is stable, and more specifically the [Host Bindings](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md) proposal.

**Comment by iddan** [comment] 2019-09-18 19:23
Not sure I understand why WASM is needed for this. The instructions can be executed directly by go. As far as I understand it we don't need a VM for this.

**Comment by dennwc** [comment] 2019-09-18 22:40
@iddan First of all, I acknowledge that I've probably misread that piece of documentation for Gremlin. But even reading through it carefully, it's still not clear to me if they only encode graph-related instructions or not. It's a bit confusing.

Because if the do, this is really a "query plan serialization" and it has nothing to do with a "bytecode" (as in JVM). The query plan serialization is cool and it's planned for Cayley, but it will always be limited to a single execution plan. This means you can not run a graph algorithm without constant interaction with a client. Which is still good enough for most use-cases.

But if they actually do use real bytecode with generic operations, then it can be called a VM in a sense. This approach has advantages, for example, you can encode a graph algorithm in this kind of bytecode and execute it on the server without interacting with the client.

Each of those two is a big feature on it's own, so can you please clarify which one you've meant?

**Comment by iddan** [comment] 2019-09-19 08:27
Oh, now I get it. Yeah, those are two different projects. I meant the "query plan serialization" when I opened the issue. I think we can start with it and when WASM is ready we can do actual byte code.

**Comment by dennwc** [comment] 2019-09-19 13:16
Then I think it's a duplicate of #668. So closing this, and will add a link for more context to that issue.

**Closed by dennwc** 2019-09-19 13:16 UTC
Labels: Feature Design, performance

**Comment by iddan** [comment] 2019-09-19 14:06
Cool, and we can revisit WASM later.
