### ISSUE TITLE
Iterator bug?

### ISSUE THREAD

**Issue by srenatus** [cayleygraph/cayley#254] opened 2015-05-21 10:42 UTC
Hi.

Having tried Cayley, I'm pleasently surprised by how nice and simple a graph database can be.

But I stumbled upon something weird (using Cayley v0.4.1 built 2015-04-25T19:37-0400, cayley_0.4.1_windows_amd64). I tried to extract a test case:

Using the quads:

```
c1 type c .
c2 type c .
c3 type c .

c1 p o .
c2 p o .
c3 q c2 .
o r o2 .
```

and the Gremlin functions:

```js
var cs = g.V().Has("type", "c")

function getr(c) {
  var rs = g.V(c).Out("p")
                 .Out("r")
                 .ToArray()
  g.Emit(rs)
}
```

`getr(cs.ToArray()[2])` gives the correct result:
```js
{
 "result": [
  []
 ]
}
```

...but `cs.ForEach(getr)` does not:

```js
{
 "result": [
  [
   "o2"
  ],
  [
   "o2"
  ],
  [
   "o2" // shouldn't be here!
  ]
 ]
}
```

I'm using the default backend, just unpacked the zip, used a git-checkout for getting the assets (in the unzipped archive, `docs/` was missing).

Any ideas? I might just try to do something stupid here, so any hints are appreciated.

Thanks a lot
Stephan

**Comment by barakmich** [comment] 2015-05-21 18:08
Thanks for the detailed report!

So I dug a little bit into it. Including finding a marshalling bug on the REPL. A little insight into what's going on: Changing the query slightly to tag the paths like this:

```
var cs = g.V().Has("type", "c")

function getr(c) {
  var rs = g.V(c).As("foo").Out("p")
                 .Out("r")
                 .TagArray()
  g.Emit(rs)
}

cs.ForEach(getr)
```

Gives the following result:
```
{
 "result": [
  [
   {
    "foo": "c1",
    "id": "o2"
   },
   {
    "foo": "c2",
    "id": "o2"
   }
  ],
  [
   {
    "foo": "c1",
    "id": "o2"
   },
   {
    "foo": "c2",
    "id": "o2"
   }
  ],
  [
   {
    "foo": "c1",
    "id": "o2"
   },
   {
    "foo": "c2",
    "id": "o2"
   }
  ]
 ]
}
```

So, it's doing something strange and probably wrong: it's doing a for each across the list of things (ie, for each of *those*) -- so you're getting the full set three times, and only returning the top result (o2) for each -- which is a little bad documentation as well as part of the cleanup surrounding getting all paths and getting top level results -- which needs to be addressed in the Go API anyway.

Plus ForEach seems to be broken somehow; since we're providing that function it's likely a bug there and not in otto (though I'm not ruling that out)

Hopefully that explains what's happening, and there does seem to be a bug here; maybe not in iterators, but certainly unexpected behavior :)

**Comment by barakmich** [comment] 2015-05-21 20:12
Followup: `getr(c)` isn't quite what you might expect it to be. It's in fact a tag map; eg the result:

```
{ "id": "c1"}
```

So changing `g.V(c)` to `g.V(c.id)` gives the correct behavior. 

Why V is treating this as "all" is another question, and the underlying bug.

**Comment by srenatus** [comment] 2015-05-22 07:37
@barakmich thanks a lot for your insights and help!

**Closed** 2016-07-17 18:02 UTC
Labels: bug
