### ISSUE TITLE
support for openCypher? 

### ISSUE THREAD

**Issue by kant111** [cayleygraph/cayley#795] opened 2019-07-06 18:08 UTC
support for openCypher natively?  Instead of doing conversions from one language to another.

**Comment by dennwc** [comment] 2019-07-08 09:27
This may be a good option, and we already have done some experiments in this direction. There are a few issues to work on, like better schema support and support for paths in query results, but nothing blocking. The only problem is the lack of dev bandwidth.

And just to mention, it will still be a "conversion from one language to another", though.

**Comment by iddan** [comment] 2019-11-13 16:12
This is a duplicate of #340

**Closed by iddan** 2019-11-13 16:12 UTC
Labels: help wanted, query languages
