### ISSUE TITLE
Strange visualization

### ISSUE THREAD

**Issue by h4ck3rm1k3** [cayleygraph/cayley#596] opened 2017-05-14 12:01 UTC
# Query 
```
g.V().Tag("a").Out("nodetype").Tag("source").Back("a").Out("idx","d").Out("nodetype").Tag("target").All()
```

# result 
```
{"result":[{"a":"@49300","d":"idx","id":"integer_cst","source":"constructor","target":"integer_cst"}]}
```

has the vis 

![example](https://i.imgur.com/fIQrKOf.png)

**Comment by dennwc** [comment] 2017-05-14 13:47
I cannot reproduce this. Maybe a problem with a browser? I'm using Chrome.
![image](https://cloud.githubusercontent.com/assets/676724/26034427/fd478522-38c4-11e7-8fb9-29449b9940df.png)

**Comment by h4ck3rm1k3** [comment] 2017-05-14 15:25
On chromium Version 55.0.2883.75 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)
 and firefox 50.0 on debian gnu linux


This does not work :
```
g.Emit({"source":"constructor","target":"integer_cst"})
```

this works :
```
g.Emit({"source":"constru2ctor","target":"integer_cst"})
```

this is worse
```
g.Emit({"source":"constructor","target":"constructor"})
``

**Comment by dennwc** [comment] 2017-05-14 15:55
Sorry, I can't reproduce this. Both works for me. It throws one node out of initial zoom level, but it's there after adjustment.

The third just draws one node without a label. The visualizer does not support self-links, I believe.

I'll close this for now, since new UI and visualizer is on the way. If problem persists in a new one, feel free to reopen.

**Closed by dennwc** 2017-05-14 15:55 UTC

**Comment by h4ck3rm1k3** [comment] 2017-05-14 16:14
sure, np
