### ISSUE TITLE
0.7 returning {Result:Null}

### ISSUE THREAD

**Issue by RossOliver3** [cayleygraph/cayley#683] opened 2018-01-17 11:29 UTC
**Description**
0.7 release of Cayley is returning Null for a get all query

**Steps to reproduce the issue:**
1. Run Cayley 0.7 using this command that works with 0.6 and was altered for 0.7 to account for the change in the way --Port was/is handled

cayley http --dbpath=./data/testdata.nq --host  0.0.0.0:64210
`
2. in CayleyUI run 'g.V().All();'

**Received results:**

```
{Result:Null}
```

**Expected results:**
A JSON object containing all of the test data

**Comment by dogfoodsilo4** [comment] 2018-01-17 11:35
I've also verified the same behaviour using Cayley 0.7.0 on Windows 386 platform.

Gizmo query: **g.V().All();**

{Result:Null}

0.6.1 works ok.

**Comment by dennwc** [comment] 2018-01-17 11:39
Duplicate of https://github.com/cayleygraph/cayley/issues/678

Short answer: change `-dbpath` to `-i`.

v0.7.1 will include the fix to accepts `dbpath` again.

**Closed by dennwc** 2018-01-17 11:39 UTC

**Comment by dogfoodsilo4** [comment] 2018-01-17 11:48
Awesome, Thank you!
