### ISSUE TITLE
MongoDB: could not retrieve data while using .Out or .In

### ISSUE THREAD

**Issue by harirehm** [cayleygraph/cayley#480] opened 2016-09-27 13:30 UTC
I'm using cayley with mongodb and gremlin query language to manipulate data. I'm able to insert the values and view all of them in my localhost:64210 when I use `g.V().All()`. I'm also getting the right values when I use `g.V().Out().All()`. When I use `g.V("node").Out("relation").All()`, I'm getting the desired result. But, when I use 'g.V("node").Out().All()', its returning null. But its supposed to return a list of nodes. Its logging the below error message in the command prompt (the one where I used cayley http).

> E0927 18:36:19.299326 07360 quadstore.go:329] Error: Couldn't retrieve node 12c6fc06c99a462375eeb3f43dfd832b08ca9e17 not found

**Note:** I'm able to achieve the above things when I use 'leveldb'.
BTW, below is my cayley.cfg
{
"database": "mongo",
"db_path": "127.0.0.1:27017",
"read_only": false
}

**Comment by dennwc** [comment] 2016-09-27 13:45
It's should be fixed upstream, if you are using Cayley v0.5.

**Comment by harirehm** [comment] 2016-09-27 15:25
What do you mean by upstream? I'm using Cayley v0.5.

**Comment by dennwc** [comment] 2016-09-27 15:47
Meaning our `master` branch. We should upload v0.6RC1 to our release page, I think.

**Comment by harirehm** [comment] 2016-09-28 03:47
So, isn't there a solution to this issue in v0.5?

**Comment by harirehm** [comment] 2016-09-28 06:15
One more update, when I use 'g.V("node").Out("relation1").Out().All()', I'm getting right results. But when I do, 'g.V("node").Out("relation1").Out("relation2").All()', I get null as results. Where am I going wrong?

**Comment by dennwc** [comment] 2016-09-28 12:15
The reason because I mentioned new release is because there's nothing wrong with your query. This might be a bug, but I haven't seen it in current dev version. We will release v0.6 today or tomorrow at most, so you can try to reproduce it on a new version.

**Comment by harirehm** [comment] 2016-10-07 06:20
When shall we expect the v0.6 release. It's not yet out.

**Comment by dennwc** [comment] 2016-10-08 10:10
Release is out: [v0.6](https://github.com/cayleygraph/cayley/releases/tag/v0.6.0)

**Comment by SharmilaRavi** [comment] 2016-10-12 06:15
.In() and .Out doesn't work in any combination when working with v0.6. Also, `g.V("node").All()` doesn't work in v0.6.

**Comment by dennwc** [comment] 2016-10-12 09:39
@SharmilaRavi I guess that you have a `<node>` in your quad file, right? If so, then your query is incorrect, and you should write it this way: `g.V("<node>").All()`. Check release notes for why this is necessary.

@harirehm I still cannot reproduce your case, at least for MongoDB v3 and path lib (which Gremlin uses).

**Comment by SharmilaRavi** [comment] 2016-10-12 12:08
Yeah we already found the issue. We missed the double quotes. Now it is working fine.
Thanks for your concern.

**Comment by harirehm** [comment] 2016-10-12 12:18
@dennwc, after updating cayley v0.6, we are not able to reproduce the defect. Not sure whether we have to follow a different format for v0.5 or it's a bug in v0.5. But as of now, .In() and .Out works perfectly with v0.6. And we followed the same procedure in v0.6 as we did in v0.5.

**Comment by dennwc** [comment] 2016-10-12 12:49
Great! Considering as resolved, then.

**Closed by dennwc** 2016-10-12 12:49 UTC
