### ISSUE TITLE
Unclear how to set ignore duplicate to true

### ISSUE THREAD

**Issue by tmlbl** [cayleygraph/cayley#465] opened 2016-08-27 02:30 UTC
Using with bolt in a program derived from the "hello bolt" example.

I am setting the `ignore_duplicate` option but still get an error on batch insertion that contains a duplicate:

``` go
    // Initialize the database
    opts := make(graph.Options)
    opts["ignore_duplicate"] = true
    graph.IgnoreDuplicates = true
    graph.InitQuadStore("bolt", dbFile.Name(), opts)

    // Open and use the database
    store, err := cayley.NewGraph("bolt", dbFile.Name(), opts)
```

`store.AddQuadSet` still returns an error for duplicate entries.

**Comment by tmlbl** [comment] 2016-08-27 02:33
Changed from `AddQuadSet` to using a transaction and it works.

**Comment by dennwc** [comment] 2017-05-14 16:27
Changed IgnoreDuplicates to true by default. Closing this, since I was not able to reproduce.

**Closed by dennwc** 2017-05-14 16:27 UTC
Labels: state: try reproduce
