### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by yurivict** [cayleygraph/cayley#978] opened 2023-05-07 17:35 UTC
0.7.7 was in 2019 which is 3.5 years ago.

**Comment by ip-rw** [comment] 2023-07-06 16:21
i'm also wondering about this. Cayley looks like it fits my requirements really rather nicely but it is a little quiet in here and on the fork front...

The appetite for Graph DBs (they're are a little bit sexy aren't they...) might actually outweigh the need for Graph DBs...

**Comment by dennwc** [comment] 2023-07-24 08:45
Duplicate of #973.

**Closed by dennwc** 2023-07-24 08:45 UTC
