### ISSUE TITLE
i/o timeout when importing to mongo

### ISSUE THREAD

**Issue by offero** [cayleygraph/cayley#439] opened 2016-07-09 21:50 UTC
I created an nquads file with 10732176 quads (256 MB), ran the http server, and POSTed the data. It inserted 5193276 quads, but then started to report timeout errors (below). The import was taking a while, but was working successfully until those errors started.

Curl:
> curl http://127.0.0.1:64210/api/v1/write/file/nquad -F NQuadFile=@routes.nq

Cayley v0.5.0 darwin amd64
Mongo DB: 2.6.12

Cayley Errors:
> ...
E0709 17:35:56.544089 97863 quadstore.go:202] Other error checking valid quad: %s %v. dd2998a86bf7469b4d4e10453e8ee8736d9c216d9f1a70c5f055ecad9d8a070413839af1a93a615d8c7ad710a361c9ece15d1dea9af44185748af36cda39a3ee5e6b4b0d3255bfef95601890afd80709 read tcp 127.0.0.1:58092->127.0.0.1:27017: i/o timeout
E0709 17:35:56.544429 97863 quadstore.go:202] Other error checking valid quad: %s %v. dd2998a86bf7469b4d4e10453e8ee8736d9c216d9f1a70c5f055ecad9d8a070413839af1a93a615db67a7b57baf2265537615ee0b627ff148457a9ddda39a3ee5e6b4b0d3255bfef95601890afd80709 read tcp 127.0.0.1:58092->127.0.0.1:27017: i/o timeout
E0709 17:35:56.544448 97863 quadstore.go:202] Other error checking valid quad: %s %v. dd2998a86bf7469b4d4e10453e8ee8736d9c216d9f1a70c5f055ecad9d8a070413839af1a93a615d73cc4f578b2a98b20b7c09713b49fc2bdc5f0921da39a3ee5e6b4b0d3255bfef95601890afd80709 read tcp 127.0.0.1:58092->127.0.0.1:27017: i/o timeout
...

**Comment by robertmeta** [comment] 2016-07-27 14:38
I was unable to reproduce this.  :(   Any specific info on your Mongo setup?

**Comment by dennwc** [comment] 2016-07-27 15:27
I also think that this might be related to mongo server, client driver (mgo) or network problem. It's unlikely that Cayley itself is related to the issue.

**Comment by dennwc** [comment] 2016-10-23 01:05
Closing this. Feel free to reopen if problem is still there in v0.6.

**Closed by dennwc** 2016-10-23 01:05 UTC
Labels: state: try reproduce
