### ISSUE TITLE
Internal server error when upload ~50MB nquad file to cayley in a container

### ISSUE THREAD

**Issue by shawnzhu** [cayleygraph/cayley#837] opened 2019-09-25 21:08 UTC
**Description**

I can not upload ~50MB nquad file over http by following this guide: https://github.com/cayleygraph/cayley/blob/master/docs/Container.md

**Steps to reproduce the issue:**
1. run `docker run -p 64210:64210 -d cayleygraph/cayley:v0.7.5`
2. visit http://localhost:64210/ui/write
3. upload an 50MB sized nquad file.

**Received results:**

got `upload completed undefined` from the web UI.

when I look at container logs, I saw:
```
I0925 20:59:50.143686       1 cayley.go:63] Cayley version: 0.7.5 (6ce5dd09d00a)
I0925 20:59:50.143883       1 cayley.go:76] using config file: etc/cayley.json
I0925 20:59:50.143981       1 database.go:187] using backend "bolt" (/data/cayley.db)
I0925 20:59:50.145913       1 http.go:186] using assets from "/assets"
I0925 20:59:50.146756       1 http.go:42] listening on :64210, web interface at http://localhost:64210
I0925 21:00:28.969080       1 http.go:89] started POST /api/v1/write/file/nquad for 172.17.0.1:53518
E0925 21:00:30.882398       1 write.go:108] open /tmp/multipart-975992773: no such file or directory
I0925 21:00:30.882723       1 http.go:91] completed 500 Internal Server Error /api/v1/write/file/nquad in 1.913702222s
I0925 21:00:31.386499       1 http.go:89] started POST /api/v1/write/file/nquad for 172.17.0.1:53514
E0925 21:00:32.480892       1 write.go:108] open /tmp/multipart-134137952: no such file or directory
I0925 21:00:32.482743       1 http.go:91] completed 500 Internal Server Error /api/v1/write/file/nquad in 1.094844471s
```

**Expected results:**

**Output of `cayley version` or commit hash:**

```
Cayley version: 0.7.5 (6ce5dd09d00a)
```

**Environment details:**

Backend database: `using backend "bolt" (/data/cayley.db)`

**Comment by shawnzhu** [comment] 2019-09-25 21:11
## Diagnose

So the error message `write.go:108] open /tmp/multipart-975992773: no such file or directory` looks interesting since it seems it buffers uploaded file as multipart file under directory `/tmp`. Since the  container image `cayleygraph/cayley:v0.7.5` is built from scratch, I assume such problem is caused by missing directory `/tmp`.

Then I tried to run cayley by running command `docker run -p 64210:64210 -d --tmpfs /tmp cayleygraph/cayley:v0.7.5`, then repeat the steps to reproduce this problem, it works very well. see container logs:

```
I0925 21:01:21.476582       1 cayley.go:63] Cayley version: 0.7.5 (6ce5dd09d00a)
I0925 21:01:21.476831       1 cayley.go:76] using config file: etc/cayley.json
I0925 21:01:21.477010       1 database.go:187] using backend "bolt" (/data/cayley.db)
I0925 21:01:21.479885       1 http.go:186] using assets from "/assets"
I0925 21:01:21.480640       1 http.go:42] listening on :64210, web interface at http://localhost:64210
I0925 21:01:52.376727       1 http.go:89] started POST /api/v1/write/file/nquad for 172.17.0.1:53550
I0925 21:02:51.092231       1 http.go:91] completed 200 OK /api/v1/write/file/nquad in 58.714533517s
```

## Conclusion

Need to update the doc.

**Comment by shawnzhu** [comment] 2019-09-25 21:27
Another possible fix is adding directory `/tmp` within the container image by updating the `Dockerfile`

**Comment by dennwc** [comment] 2019-09-25 21:45
@shawnzhu Thanks for reporting this issue! I can verify that this is indeed a standard behavior of a Go http library for large multipart files.

The problem is that our WebUI is old and uses HTTP API v1 which sends files as multipart. In API v2 we use request body directly, so no temp file is required (cc @iddan for notes for the new UI).

Can you please try creating a `Dockerfile` with a `/tmp` directory to see if it solves the issue? For example:

```Dockerfile
FROM cayleygraph/cayley:v0.7.5

RUN mkdir /tmp
```

Or by starting a container, `exec`ing `mkdir` inside, and trying to upload the file again:

```bash
docker run -p 64210:64210 -d --name cayley cayleygraph/cayley:v0.7.5
docker exec cayley mkdir /tmp
```

I would prefer to fix the container instead of adding more flags to docs to make it just work our of the box.

**Comment by shawnzhu** [comment] 2019-09-26 13:34
> Can you please try creating a Dockerfile with a /tmp directory to see if it solves the issue? For example:
```Dockerfile
FROM cayleygraph/cayley:v0.7.5

RUN mkdir /tmp
```

When building a container image from this `Dockerfile`, I got:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM cayleygraph/cayley:v0.7.5
 ---> 958c53b1062b
Step 2/2 : RUN mkdir /tmp
 ---> Running in 0d84ca83db23
OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

This is caused by the base container image cayleygraph/cayley:v0.7.5 is built from scratch contains no shell at all.

I've created a new PR to fix the docker image and I confirm it fixes this issue.

**Comment by dennwc** [comment] 2019-09-26 14:04
Thanks, merged! Yeah, I forgot that a different syntax must be used since there is no shell in our image.

**Closed** 2019-09-26 14:03 UTC
