### ISSUE TITLE
Inconsistent Data After Import into Mongodb

### ISSUE THREAD

**Issue by githistory** [cayleygraph/cayley#222] opened 2015-03-18 04:13 UTC
### How to Reproduce
1. Spin cayley up and running with mongodb as store.
2. Upload the film data contained in google/cayley github repo into cayley.
3. Run below query
```javascript
g.V('Casa de Areia').As('source').In('name').Out('/film/film/starring').Out('/film/performance/actor').Out('name').As('target').All()
```

### Expected Behavior
Cayley should return below result set
```javascript
{
 "result": [
  {
   "id": "João Acaiabe",
   "source": "Casa de Areia",
   "target": "João Acaiabe"
  },
  {
   "id": "Haroldo Costa",
   "source": "Casa de Areia",
   "target": "Haroldo Costa"
  },
  {
   "id": "Fernanda Montenegro",
   "source": "Casa de Areia",
   "target": "Fernanda Montenegro"
  },
  {
   "id": "Fernanda Torres",
   "source": "Casa de Areia",
   "target": "Fernanda Torres"
  }
 ]
}
```

### Observed Behavior
Cayley returns below instead
```javascript
{
 "result": [
  {
   "id": "João Acaiabe",
   "source": "Casa de Areia",
   "target": "João Acaiabe"
  },
  {
   "id": "_:47623",
   "source": "Casa de Areia",
   "target": "_:47623"
  },
  {
   "id": "Fernanda Montenegro",
   "source": "Casa de Areia",
   "target": "Fernanda Montenegro"
  },
  {
   "id": "Fernanda Torres",
   "source": "Casa de Areia",
   "target": "Fernanda Torres"
  }
 ]
}
```

### A Look at DB
It seems the data in db is correct
```javascript
{
    "_id" : "d92307b7ed1da6d6e681c2d288e4015063aceb156ae999552a0d2dca14d62e2bc8b764d377b1dd6c63dbe9562fa5c4253ab95f0ebf20deeb30bfdf20da39a3ee5e6b4b0d3255bfef95601890afd80709",
    "subject" : "/en/haroldo_costa",
    "predicate" : "name",
    "object" : "Haroldo Costa",
    "label" : "",
    "Added" : [ 
        NumberLong(240299)
    ]
}
```

The data returned by cayley is correct up till `.Out('/film/performance/actor')`
```javascript
{
 "result": [
  {
   "id": "/en/joao_acaiabe",
   "source": "Casa de Areia",
   "target": "/en/joao_acaiabe"
  },
  {
   "id": "/en/haroldo_costa",
   "source": "Casa de Areia",
   "target": "/en/haroldo_costa"
  },
  {
   "id": "/en/fernanda_montenegro",
   "source": "Casa de Areia",
   "target": "/en/fernanda_montenegro"
  },
  {
   "id": "/en/fernanda_torres",
   "source": "Casa de Areia",
   "target": "/en/fernanda_torres"
  }
 ]
}
```

But cried when the final `.Out('name')` is reached ( See Observed Behavior ).

**Comment by kortschak** [comment] 2015-03-18 05:27
Would you post the terminal output when you start cayley with `-logtostderr -v=2`.

**Comment by kortschak** [comment] 2015-03-18 05:37
Also, what result do you get for simple queries like this:

```
g.V('Haroldo Costa').As('source').In('name').Out('name').As('target').All()```

**Comment by starhawkhkk** [comment] 2015-03-18 06:48
I restarted both mongodb and cayley containers and re-run below query
```javascript
g.V('Casa de Areia').As('source').In('name').Out('/film/film/starring').Out('/film/performance/actor').Out('name').As('target').All()
```

This time, magically, correct results are returned
```javascript
{
 "result": [
  {
   "id": "João Acaiabe",
   "source": "Casa de Areia",
   "target": "João Acaiabe"
  },
  {
   "id": "Haroldo Costa",
   "source": "Casa de Areia",
   "target": "Haroldo Costa"
  },
  {
   "id": "Fernanda Montenegro",
   "source": "Casa de Areia",
   "target": "Fernanda Montenegro"
  },
  {
   "id": "Fernanda Torres",
   "source": "Casa de Areia",
   "target": "Fernanda Torres"
  }
 ]
}
```

Seems the problematic results are returned only when the data is just imported and containers are not yet restarted.

**Comment by dennwc** [comment] 2016-07-09 13:16
Can't reproduce on HEAD. Closing.

**Closed by dennwc** 2016-07-09 13:16 UTC
Labels: state: try reproduce
