### ISSUE TITLE
Is the Cassandra-backend branch still in develop?

### ISSUE THREAD

**Issue by ustczen** [cayleygraph/cayley#350] opened 2015-11-28 04:53 UTC
In my opinion, With the emergence of ScyllaDB, a Cassandra backend  would be the "killer backend" of cayley. But the last commit of Cassandra-beckend branch appears at 8 month ago..

**Comment by oren** [comment] 2015-11-28 07:34
Related question from ScyllaDB's group: https://groups.google.com/forum/#!topic/scylladb-users/_IewBKoa7Ek

**Comment by jcmartins** [comment] 2016-02-11 12:15
+1 to Scylla backend

**Comment by dennwc** [comment] 2016-07-03 20:37
Considering as a duplicate of #20

**Closed by dennwc** 2016-07-03 20:37 UTC
Labels: New Backends, state: PR
