### ISSUE TITLE
Cayley v0.7.0 always returns null for all the queries that work with previous versions

### ISSUE THREAD

**Issue by droidresearch** [cayleygraph/cayley#678] opened 2018-01-07 07:31 UTC
**Description**

The cayley version v0.7.0 always returns null for any queries. The same queries with the same data file work fine with v0.6.1
**Steps to reproduce the issue:**
1. Extract cayley v0.7.0
2. run ./cayley http --dbpath=data/testdata.nq 
3. Open browser and go to http://localhost:64210 and run the query 
g.V("<bob>").In("<follows>").All()

4. The result will be null

Do the same with v0.6.1, you will get results

**Received results:**

```
null
```
![image](https://user-images.githubusercontent.com/14039691/34647506-7e65a3b4-f3aa-11e7-885c-4fd45e491c8a.png)
![image](https://user-images.githubusercontent.com/14039691/34647507-875e4b24-f3aa-11e7-8617-49e9d879ffa6.png)

**Expected results:**

**Output of `cayley version` or commit hash:**

```
Cayley version: 0.7.0
Git commit hash: 6f8446e4171ebc84955dd0ff91927510ba1aee16
Build date: 2017-12-24T17:51:48Z
```

**Environment details:**
macOS High Sierra 10.13.2
Backend database: `no database`

**Comment by dennwc** [comment] 2018-01-07 09:49
Duplicate of #677

**Closed by dennwc** 2018-01-07 09:49 UTC
